export type LegalBlock = { kind: 'title' | 'section' | 'paragraph'; text: string };

function toBlocks(items: string[]): LegalBlock[] {
  return items.map((text, index) => {
    if (index === 0) return { kind: 'title', text };
    if (/^\d+(\.|\s-)/.test(text) || /^[A-Z??????????? ]{8,}$/.test(text)) {
      return { kind: 'section', text };
    }
    return { kind: 'paragraph', text };
  });
}

export const PRIVACY_UPDATED_AT = '11 de maio de 2026';
export const TERMS_UPDATED_AT = '11 de maio de 2026';

const privacyItems = [
  "POLÍTICA DE PRIVACIDADE - PLATAFORMA URBAN AI",
  "Esta Política de Privacidade explica, em linguagem simples, como a Urban AI coleta, usa, guarda e compartilha as suas informações pessoais. Queremos que você entenda exatamente o que acontece com os seus dados — sem termos difíceis e sem letras miúdas.",
  "Se tiver qualquer dúvida depois de ler este documento, é só entrar em contato pelo e-mail privacidade@myurbanai.com. Prometemos responder em até 15 dias.",
  "1. Quem é responsável pelos seus dados?",
  "A empresa responsável pela plataforma Urban AI e por todas as decisões sobre como os seus dados são tratados, é a MP IA Tecnologia Ltda, inscrita no CNPJ 62.497.936/0001-27, com sede em São Paulo/SP.",
  "A operação técnica do dia a dia da plataforma é realizada pela empresa Guilds, inscrita no CNPJ 44.361.255/0001-55, que trabalha em nome da MP IA Tecnologia e segue todas as mesmas regras de proteção de dados.",
  "Para questões relacionadas à sua privacidade, você pode falar conosco pelo canal oficial:",
  "E-mail: privacidade@myurbanai.com",
  "Prazo de resposta: até 15 dias corridos",
  "Estamos em processo de designar formalmente um Encarregado de Proteção de Dados (também chamado de DPO), conforme exige a lei brasileira. Assim que isso estiver concluído, publicaremos o nome e o contato dessa pessoa aqui nesta Política.",
  "2. O que é a Urban AI e o que ela faz?",
  "A Urban AI é uma plataforma digital que ajuda anfitriões de aluguel por temporada, como proprietários de imóveis no Airbnb, a definir o melhor preço de diária para seus imóveis. Para isso, nossa tecnologia analisa dados de mercado, sazonalidade, eventos na região e características do imóvel, e gera uma sugestão de preço.",
  "É importante deixar claro: a sugestão de preço é apenas uma recomendação. Você, como anfitrião, decide se vai ou não usá-la. Mesmo no modo automático, em que o preço é enviado diretamente para o canal de distribuição, você ativa e desativa esse recurso quando quiser.",
  "A Urban AI é uma ferramenta de apoio à sua decisão. Nós não somos uma imobiliária, não prestamos consultoria jurídica ou financeira e não garantimos que o uso da plataforma vai aumentar sua receita. Os resultados dependem de muitos fatores que estão fora do nosso controle, como o comportamento do mercado, a qualidade do seu imóvel e as preferências dos hóspedes.",
  "3. Quais informações coletamos sobre você?",
  "Coletamos apenas as informações necessárias para que a plataforma funcione bem. Veja o que isso significa na prática:",
  "Quando você cria uma conta, pedimos seu nome completo, e-mail e senha. O telefone e o nome da empresa (para administradoras) são opcionais.",
  "Sua senha nunca é armazenada em texto aberto, ela passa por um processo de criptografia que a torna ilegível para qualquer pessoa, inclusive para nós.",
  "Quando você cadastra um imóvel, informamos o endereço, o tipo de imóvel, o número de quartos, banheiros e camas, as fotos e o identificador público do seu anúncio no Airbnb.",
  "Com esse identificador, buscamos dados públicos do seu anúncio (como avaliações e tipo de propriedade) para deixar as sugestões de preço mais precisas. As fotos não ficam armazenadas em nossos servidores, usamos apenas o link público que já existe no Airbnb.",
  "Quando você usa a plataforma, registramos automaticamente algumas informações técnicas, como o endereço IP do seu acesso, o tipo de navegador e dispositivo que você está usando e os horários de entrada e saída. Essas informações são usadas para garantir a segurança da sua conta. Por exemplo, para detectar acessos suspeitos.",
  "Quando você assina um plano pago, o pagamento é processado pelo Stripe, uma empresa especializada em pagamentos. Nós não temos acesso ao número do seu cartão de crédito. O Stripe cuida dessas informações com alto padrão de segurança.",
  "Se você se inscreveu na lista de espera antes do lançamento, guardamos apenas seu e-mail e sua posição na fila.",
  "Não coletamos dados sensíveis como informações de saúde, origem racial, religião, orientação sexual ou dados biométricos. Também não coletamos documentos de identidade.",
  "4. Para que usamos suas informações?",
  "Usamos seus dados exclusivamente para fazer a plataforma funcionar para você. Em termos práticos, isso significa:",
  "Para criar e manter a sua conta: precisamos do seu e-mail e senha para que você possa entrar na plataforma com segurança.",
  "Para gerar as sugestões de preço: usamos os dados do seu imóvel, combinados com informações públicas de mercado, para calcular a melhor recomendação de diária para cada dia do calendário.",
  "Para processar o pagamento da sua assinatura: compartilhamos o mínimo necessário com o Stripe para que a cobrança seja realizada e a sua assinatura seja mantida ativa.",
  "Para enviar e-mails importantes: como confirmação de cadastro, avisos sobre a sua assinatura, alertas de cota de imóveis e recuperação de senha. Esses e-mails são enviados porque são parte do serviço que você contratou, você não precisa se inscrever separadamente para recebê-los.",
  "Para manter a plataforma segura: registramos acessos e monitoramos erros técnicos para detectar problemas, prevenir fraudes e responder a incidentes de segurança.",
  "Para melhorar as sugestões de preço: usamos dados históricos de preços de forma completamente anonimizada, ou seja, sem identificar você para melhorar continuamente o nosso motor de inteligência artificial. Mesmo que você cancele sua conta, esses dados anônimos continuam sendo utilizados, pois ninguém mais consegue associá-los a você.",
  "Não usamos seus dados para enviar publicidade sem que você peça. No futuro, se criarmos um newsletter ou comunicações de marketing, você precisará se inscrever voluntariamente, e poderá cancelar essa inscrição quando quiser.",
  "5. Com quem compartilhamos suas informações?",
  "Compartilhamos seus dados somente com empresas que nos ajudam a operar a plataforma. Essas empresas atuam como nossas parceiras técnicas e só podem usar seus dados para as finalidades que nós determinamos, nunca para fins próprios delas.",
  "As principais parceiras são:",
  "Operação técnica da plataforma: nossa empresa parceira de desenvolvimento tem acesso aos dados necessários para manter, desenvolver e dar suporte ao sistema, incluindo dados de conta e dados de imóveis. Ela atua exclusivamente em nosso nome e sob nossas instruções.",
  "Processamento de pagamentos: compartilhamos seu nome, e-mail e CPF com o processador de pagamentos para verificar sua identidade e habilitar a cobrança recorrente do seu plano. Os dados do seu cartão de crédito são tratados diretamente por esse serviço, nós não temos acesso a eles.",
  "Envio de e-mails transacionais: compartilhamos seu nome e endereço de e-mail com o serviço de disparo de mensagens para entregar comunicações essenciais, como recibos de pagamento, notificações de conta e alertas de cota.",
  "Hospedagem da plataforma: todos os dados que você nos fornece ficam armazenados nos servidores da nossa provedora de infraestrutura, sempre de forma criptografada. Esse armazenamento é necessário para que a plataforma funcione.",
  "Geolocalização e login por conta de terceiro: o endereço do seu imóvel é enviado a um serviço de mapas para conversão em coordenadas geográficas, dado necessário para o cálculo de preços. Se você optar pelo login social, seus dados de autenticação são verificados pelo respectivo provedor de identidade. Para análise de eventos públicos da região, não enviamos nenhum dado seu a serviços externos.",
  "Consulta de dados públicos do anúncio: para enriquecer as sugestões de preço, enviamos o identificador público do seu anúncio a um serviço de dados, o mesmo código que qualquer pessoa pode ver na URL do Airbnb. Nenhum dado pessoal identificador é compartilhado nessa etapa.",
  "Monitoramento de erros técnicos: quando ocorre uma falha na plataforma, dados técnicos, como endereço IP e identificador de sessão, são enviados automaticamente ao nosso sistema de rastreamento de erros para que a equipe possa corrigir o problema. Esse serviço possui filtros automáticos para minimizar a captura de dados pessoais.",
  "Envio automático de preços ao canal de distribuição: quando essa funcionalidade estiver disponível, as sugestões de preço geradas pelo nosso motor de IA serão enviadas diretamente ao channel manager que você utilizar. Nenhum dado pessoal adicional será compartilhado além do necessário para a autenticação da integração, e ela só será ativada com a sua autorização expressa.",
  "Não vendemos, alugamos nem comercializamos seus dados pessoais com nenhuma outra empresa ou pessoa, em nenhuma circunstância.",
  "Além dos listados acima, podemos compartilhar seus dados se formos obrigados por lei ou ordem judicial, ou para nos defender em processos legais.",
  "6. Seus dados saem do Brasil?",
  "Sim, alguns dos nossos parceiros técnicos estão localizados nos Estados Unidos e em outros países. Isso significa que parte dos seus dados pode ser processada fora do Brasil.",
  "Isso é permitido pela lei brasileira de proteção de dados (LGPD), desde que esses parceiros ofereçam um nível de proteção equivalente ao nosso. Todos os nossos parceiros internacionais assinaram acordos específicos de proteção de dados que garantem que suas informações serão tratadas com o mesmo cuidado que teríamos aqui no Brasil.",
  "7. O que acontece com dados de hóspedes?",
  "A Urban AI não se comunica diretamente com os hóspedes dos anfitriões em nenhuma situação. Os hóspedes não têm conta na plataforma e não são afetados pelo uso que você faz dela.",
  "No futuro, com a integração com o channel manager Stays, poderemos receber, com a sua autorização, o histórico de reservas do seu imóvel. Esse histórico pode conter informações básicas sobre reservas passadas, como datas e valores.",
  "Esses dados serão usados única e exclusivamente para deixar as sugestões de preço mais precisas. Eles não serão compartilhados com ninguém, não serão usados para entrar em contato com os hóspedes e passarão por um processo de anonimização antes de qualquer análise.",
  "Você só poderá ativar essa integração depois de concordar expressamente com ela em uma tela dedicada, que explicará exatamente o que será recebido e para que será usado.",
  "8. Cookies: o que são e como usamos?",
  "Cookies são pequenos arquivos que ficam salvos no seu navegador quando você acessa um site. Eles ajudam a manter você logado, lembrar suas preferências e entender como as pessoas usam a plataforma.",
  "Usamos três tipos de cookies:",
  "Cookies essenciais: são necessários para que a plataforma funcione. Sem eles, você não consegue fazer login nem navegar pelo sistema. Não é possível desativá-los sem deixar de usar a plataforma.",
  "Cookies de análise: nos ajudam a entender como os usuários navegam pela plataforma, para que possamos melhorá-la. Esses cookies são anonimizados, não identificam você pessoalmente. Você pode escolher não os ativar quando aparecer o aviso de cookies na sua primeira visita.",
  "Cookies de marketing: são usados para entender se nossas campanhas publicitárias estão funcionando. Você também pode escolher não ativá-los no aviso de cookies.",
  "Na sua primeira visita à plataforma, aparecerá uma mensagem perguntando quais cookies você aceita além dos essenciais. Você pode mudar essa escolha a qualquer momento.",
  "9. Por quanto tempo guardamos seus dados?",
  "Guardamos seus dados pelo tempo necessário para prestar o serviço e cumprir as obrigações legais. Aqui está um resumo simples:",
  "Dados da sua conta (nome, e-mail, configurações): ficam guardados enquanto você tiver uma conta ativa. Depois que você cancela, removemos ou anonimizamos seus dados pessoais em até 30 dias.",
  "Dados financeiros e fiscais (informações de pagamento, CPF coletado pelo Stripe): a lei brasileira exige que guardemos esses dados por 5 anos, mesmo após o cancelamento. Isso é uma obrigação legal, não uma escolha nossa.",
  "Registros de acesso (endereço IP, tipo de navegador): ficam guardados por 90 dias, para garantir a segurança da sua conta.",
  "Dados de erros técnicos (Sentry): ficam guardados por 30 a 90 dias, dependendo do plano do serviço.",
  "Dados anonimizados de preços: esses dados não identificam você e são usados para melhorar o motor de IA. Eles ficam guardados por tempo indeterminado, pois não são mais dados pessoais depois da anonimização.",
  "Se você participou da lista de espera antes do lançamento, seus dados ficam guardados até você se tornar cliente ou pedir para ser removido da lista.",
  "10. Como protegemos suas informações?",
  "Levamos a segurança dos seus dados muito a sério. Aqui estão as principais medidas que adotamos:",
  "Sua senha é criptografada antes de ser salva, nem nós conseguimos ver qual é. Toda a comunicação entre o seu navegador e a plataforma é protegida por criptografia (o cadeado que aparece na barra de endereços). Os dados armazenados nos nossos servidores também ficam criptografados.",
  "Quando você faz login, o sistema registra o acesso e detecta automaticamente se alguém tentar usar o mesmo código de segurança em dois lugares ao mesmo tempo. Nesse caso, todas as sessões são encerradas imediatamente para proteger sua conta.",
  "Fazemos cópias de segurança do banco de dados todos os dias. Em caso de problema técnico, conseguimos restaurar as informações rapidamente.",
  "O acesso aos dados é restrito: apenas as pessoas que precisam deles para trabalhar têm permissão de acesso, e cada uma tem um nível de acesso compatível com sua função.",
  "Se você encontrar alguma vulnerabilidade de segurança na plataforma, pedimos que nos avise pelo e-mail privacidade@myurbanai.com antes de tornar o problema público. Temos um prazo de até 90 dias para corrigir o problema.",
  "11. O que acontece se houver um vazamento de dados?",
  "Se acontecer algum incidente que coloque seus dados em risco, agiremos imediatamente.",
  "Primeiro, nossa equipe avalia a gravidade do problema em até 24 horas. Se o risco for considerado relevante, comunicamos a Autoridade Nacional de Proteção de Dados (ANPD) em até 72 horas, prazo exigido por lei.",
  "Em seguida, avisamos por e-mail todos os usuários que possam ter sido afetados, explicando o que aconteceu, quais dados foram envolvidos e o que estamos fazendo para resolver o problema.",
  "Registramos tudo o que aconteceu e as medidas que adotamos, para que possamos aprender com o incidente e evitar que se repita.",
  "12. Quais são os seus direitos?",
  "A lei brasileira de proteção de dados (LGPD) garante a você uma série de direitos sobre seus dados pessoais. Veja o que você pode fazer:",
  "Saber o que guardamos: você pode pedir uma cópia de todas as informações que temos sobre você.",
  "Corrigir informações erradas: se algum dado estiver desatualizado ou incorreto, você pode pedir a correção. Muitas informações você mesmo consegue atualizar diretamente na área de perfil da plataforma.",
  "Pedir a exclusão dos seus dados: se você cancelar sua conta, seus dados pessoais serão removidos em até 30 dias, com exceção dos dados que a lei exige que guardemos por mais tempo, como os financeiros.",
  "Revogar uma autorização: se você deu permissão para algo (como o Modo Automático ou os cookies de análise), pode cancelar essa permissão quando quiser.",
  "Saber com quem compartilhamos seus dados: esta Política já explica isso, mas você pode pedir mais detalhes a qualquer momento.",
  "Pedir uma revisão humana: se você achar que uma decisão automatizada da plataforma te prejudicou (como uma sugestão de preço que não faz sentido para o seu caso), pode pedir que uma pessoa da nossa equipe revise essa situação.",
  "Se opor ao uso dos seus dados: em alguns casos, você pode pedir que paremos de usar suas informações para determinada finalidade.",
  "Reclamar para a autoridade competente: se achar que seus direitos não estão sendo respeitados, você pode reclamar diretamente à Autoridade Nacional de Proteção de Dados (ANPD), em https://www.gov.br/anpd.",
  "Para exercer qualquer um desses direitos, entre em contato pelo e-mail privacidade@myurbanai.com. Você também pode atualizar seus dados diretamente na plataforma, na página de perfil, e cancelar sua conta na página \"Meu Plano\".",
  "13. Crianças e adolescentes",
  "A Urban AI é uma plataforma destinada exclusivamente a maiores de 18 anos. Não coletamos intencionalmente dados de crianças ou adolescentes.",
  "Se descobrirmos que algum dado de menor de idade foi coletado sem querer, excluiremos essas informações imediatamente.",
  "14. Inteligência artificial: como funciona e quais são os seus limites?",
  "O coração da Urban AI é um motor de inteligência artificial que analisa dados de mercado e gera sugestões de preço para o seu imóvel. Esse motor é treinado com informações agregadas e anonimizadas de vários imóveis, nenhum dado identificável seu é usado no treinamento.",
  "As sugestões do motor são baseadas em estatísticas e padrões de mercado. Elas podem não acertar em todas as situações, e por isso você sempre tem a palavra final sobre qual preço aplicar.",
  "Também usamos o LLMs para analisar eventos públicos que podem impactar a demanda na sua região, como shows, congressos e jogos. Nenhum dado seu é enviado para esse serviço.",
  "A plataforma também tem um assistente de conversa que você pode usar para tirar dúvidas sobre os seus imóveis.",
  "15. Se esta Política mudar",
  "Podemos atualizar esta Política de Privacidade de tempos em tempos, para refletir mudanças na plataforma ou na legislação.",
  "Se for uma mudança pequena, como uma correção de texto, atualizamos a data de \"Última atualização\" no início do documento.",
  "Se for uma mudança importante que afete seus direitos, avisaremos com pelo menos 30 dias de antecedência por e-mail. Você terá tempo para decidir se concorda com as novas condições. Se não concordar, poderá cancelar sua conta sem nenhuma penalidade.",
  "A versão mais recente desta Política estará sempre disponível em https://myurbanai.com/privacidade.",
  "16. Lei aplicável e foro",
  "Esta Política é regida pelas leis brasileiras, em especial a Lei nº 13.709/2018 (LGPD), o Marco Civil da Internet (Lei nº 12.965/2014), o Código Civil e o Código de Defesa do Consumidor.",
  "Em caso de disputas, fica eleito o Foro da Comarca de Barueri/SP. Se você for consumidor pessoa física, prevalece o foro do seu domicílio, conforme o artigo 101, I, do Código de Defesa do Consumidor.",
  "São Paulo, junho de 2026.",
  "MP IA Tecnologia Ltda — Urban AI",
  "CNPJ 62.497.936/0001-27"
] as const;
const termsItems = [
  "TERMOS DE USO DA PLATAFORMA URBAN AI",
  "1. APRESENTAÇÃO E ACEITAÇÃO",
  "1.1. Os presentes Termos de Uso (“Termos”) regulam o acesso e a utilização da plataforma digital Urban AI, sistema web de inteligência de mercado e precificação dinâmica para o setor de aluguel por temporada, desenvolvida e operada pela MP IA Tecnologia Ltda, pessoa jurídica de direito privado, inscrita no CNPJ sob o nº 62.497.936/0001-27, com sede na Rua Doutor Cesar, nº 530, conjunto 804, Santana, São Paulo/SP, CEP 02013-002 (?Urban AI? ou ?Plataforma?).",
  "1.2. A Plataforma é acessível por meio do endereço eletrônico https://app.myurbanai.com, bem como do domínio institucional https://myurbanai.com.",
  "1.3. A infraestrutura técnica e a operação contínua da Plataforma são executadas pela empresa Gustavo Gouveia Macedo LTDA, inscrita no CNPJ sob o nº 44.361.255/0001-55, nome fantasia Guilds (“Guilds” ou “Operadora Técnica”), na qualidade de prestadora de serviços tecnológicos e suboperadora declarada nos termos da Lei nº 13.709/2018 (LGPD), atuando em nome e sob as instruções da MP IA Tecnologia Ltda. A Guilds não é parte contratante perante o Usuário para fins de responsabilidade pelas funcionalidades e serviços da Plataforma.",
  "1.4. Ao acessar, cadastrar-se ou utilizar a Plataforma, o Usuário declara ter lido, compreendido e aceito integralmente estes Termos, bem como a Política de Privacidade disponível em https://myurbanai.com/privacidade, que integra este instrumento para todos os fins legais, nos termos dos artigos 421 e 425 do Código Civil (Lei nº 10.406/2002) e do artigo 8º da Lei nº 12.965/2014 (Marco Civil da Internet).",
  "1.5. Caso o Usuário não concorde com qualquer disposição destes Termos, deverá abster-se de acessar ou utilizar a Plataforma.",
  "1.6. A Urban AI reserva-se o direito de modificar estes Termos a qualquer tempo, nos termos da Cláusula 14. A continuidade do uso da Plataforma após a publicação de versão atualizada implica aceitação das alterações.",
  "2. DEFINIÇÕES",
  "Para os fins destes Termos, os seguintes termos terão os significados a eles atribuídos:",
  "I. \"Plataforma\" ou \"Urban AI\": o sistema web de inteligência de mercado e precificação dinâmica para anfitriões de aluguel por temporada, incluindo código-fonte, motor de IA, banco de dados, interfaces, funcionalidades, integrações e demais componentes técnicos, acessível em https://app.myurbanai.com.",
  "II. \"Controladora\": MP IA Tecnologia Ltda (CNPJ 62.497.936/0001-27), responsável legal pela Plataforma e controladora dos dados pessoais, nos termos da LGPD.",
  "III. \"Operadora Técnica\" ou \"Guilds\": Gustavo Gouveia Macedo LTDA (CNPJ 44.361.255/0001-55), prestadora do serviço contínuo de operação técnica da Plataforma em nome da Controladora.",
  "IV. \"Usuário\" ou \"Anfitrião\": pessoa física maior de 18 (dezoito) anos ou pessoa jurídica que se cadastra na Plataforma para utilizar os serviços de precificação e gestão de imóveis de aluguel por temporada.",
  "V. \"Imóvel\": unidade habitacional cadastrada pelo Usuário na Plataforma para fins de precificação dinâmica.",
  "VI. \"Motor de IA\" ou \"Motor de Recomendação\": algoritmo proprietário de aprendizado de máquina (KNN híbrido) desenvolvido pela Urban AI para geração de sugestões de preço de diária.",
  "VII. \"Recomendação de Preço\": sugestão de preço de diária gerada pelo Motor de IA com base em dados de mercado, características do imóvel, sazonalidade, eventos e demanda, sem caráter vinculante.",
  "VIII. \"Modo Notificação\": modalidade em que o Usuário recebe a Recomendação de Preço e decide, por conta própria, aplicá-la manualmente no canal de distribuição de sua preferência.",
  "IX. \"Modo Automático\": modalidade futura, condicionada à integração com plataformas de channel manager (como Airbnb e Stays), em que o Usuário autoriza expressamente o envio automático de preços ao canal conectado, mediante consentimento específico e revogável a qualquer tempo.X. “Administradora de Temporada” ou \"PMC\" (Property Management Company): administradora de temporada que gerencia carteira de múltiplos imóveis.",
  "X. \"Assinatura\": contratação paga dos serviços da Plataforma em um dos ciclos disponíveis, com cobrança por imóvel cadastrado.",
  "XI. \"Plano\": conjunto de condições comerciais aplicáveis a determinada Assinatura, incluindo ciclo de cobrança, quantidade de imóveis contratados e condições de reajuste.",
  "XII. \"LGPD\": Lei nº 13.709/2018 — Lei Geral de Proteção de Dados Pessoais.",
  "XIII. \"Hóspede\": terceiro que realiza reservas junto ao Anfitrião, não possuindo conta na Plataforma e não sendo parte contratante destes Termos.",
  "3. OBJETO E NATUREZA DO SERVIÇO",
  "3.1. A Plataforma Urban AI tem por objeto oferecer ao Usuário ferramentas tecnológicas de apoio à decisão de precificação de imóveis para aluguel por temporada, mediante disponibilização de:",
  "I. Motor de recomendação de preço baseado em inteligência artificial (KNN híbrido);",
  "II. Painel de monitoramento de mercado, com análise de comparáveis, sazonalidade e eventos;",
  "III. Cadastro e enriquecimento de dados de imóveis;",
  "IV. Dashboard de receita estimada, ocupação e análise comparativa;",
  "V. Assistente conversacional in-app para consultas sobre os imóveis cadastrados;",
  "VI. Integração com plataformas de channel manager para envio automatizado de preços (Modo Automático), mediante consentimento expresso.",
  "3.2. Os serviços prestados pela Plataforma constituem exclusivamente prestação de serviços tecnológicos e licenciamento de software, com natureza de obrigação de meio. A Urban AI disponibiliza infraestrutura, ferramentas e recomendações analíticas, mas não presta serviços de assessoria imobiliária, consultoria jurídica, consultoria fiscal, consultoria contábil ou qualquer atividade-fim do setor de hospedagem.",
  "3.3. As Recomendações de Preço geradas pelo Motor de IA são insumos de apoio à decisão do Usuário, baseadas em modelos estatísticos e dados de mercado disponíveis no momento da análise. A Urban AI não garante, em hipótese alguma:",
  "I. Aumento de receita, ocupação ou rentabilidade do imóvel;",
  "II. Acerto dos preços sugeridos em qualquer período específico;",
  "III. Conformidade das sugestões com flutuações imprevisíveis de mercado;",
  "IV. Resultado financeiro específico decorrente da adoção das recomendações.",
  "3.4. A decisão de aplicar, modificar ou rejeitar qualquer Recomendação de Preço é de responsabilidade exclusiva do Usuário. No Modo Automático, o Usuário autoriza expressamente a aplicação, podendo revogar essa autorização a qualquer momento pela Plataforma.",
  "3.5. A Urban AI não opera canais de distribuição como Airbnb, Stays ou qualquer outra plataforma de hospedagem. A Plataforma é independente e se conecta a esses canais exclusivamente com a autorização expressa do Usuário, não sendo responsável por políticas, disponibilidade ou alterações de tais canais.",
  "3.6. O resultado financeiro obtido pelo Anfitrião depende de fatores externos alheios ao controle da Urban AI, incluindo, sem limitação: qualidade e veracidade dos dados inseridos pelo Usuário, comportamento do mercado local, sazonalidade, condições macroeconômicas, ações dos canais de distribuição, interação dos hóspedes e decisões operacionais do próprio Anfitrião.",
  "4. PERFIS DE USUÁRIO E CONDIÇÕES DE ACESSO",
  "4.1. Poderão criar conta na Plataforma:",
  "I. Anfitriões pessoa física maiores de 18 (dezoito) anos;",
  "II. Anfitriões na condição de Microempreendedor Individual (MEI);",
  "III. Microempresas e pequenas e médias empresas do setor de hospedagem por temporada;",
  "IV. Administradoras de temporada (Property Management Companies “PMCs”).",
  "4.2. É expressamente vedado o cadastro de menores de 18 (dezoito) anos como titulares de conta na Plataforma. Ao criar uma conta, o Usuário declara expressamente ter idade igual ou superior a 18 (dezoito) anos.",
  "4.3. Em caso de conta empresarial (PMC ou pessoa jurídica), a conta é vinculada ao responsável legal pela empresa. O acesso multiusuário, quando disponibilizado, estará sujeito a condições específicas.",
  "5. CADASTRO, AUTENTICAÇÃO E SEGURANÇA DA CONTA",
  "5.1. O cadastro na Plataforma pode ser realizado por:",
  "I. Cadastro manual com e-mail e senha; ou",
  "II. Login social via conta Google (OAuth).",
  "5.2. Durante o período de pré-lançamento, os novos cadastros serão integrados à lista de espera (waitlist) da Plataforma. Usuários da waitlist receberão comunicações sobre o lançamento e sua posição na fila, podendo convidar outros usuários para avançar em sua posição.",
  "5.3. O Usuário é inteiramente responsável pela guarda e confidencialidade de suas credenciais de acesso (login e senha). É vedado compartilhar credenciais com terceiros não autorizados. Toda ação realizada a partir das credenciais do Usuário será presumida como de sua autoria.",
  "5.4. Em caso de suspeita de acesso não autorizado ou comprometimento de credenciais, o Usuário deve comunicar imediatamente a Urban AI pelo e-mail suporte@myurbanai.com.",
  "5.5. A Urban AI adota medidas técnicas de segurança como: armazenamento de senhas com criptografia bcrypt, tokens JWT em cookies HttpOnly com detecção de reutilização, criptografia em trânsito (HTTPS/TLS 1.3) e em repouso (AES-256), além de rate limiting nas rotas de autenticação.",
  "5.6. O Usuário reconhece que nenhuma medida de segurança é absolutamente infalível e que a Urban AI não pode ser responsabilizada por acessos não autorizados decorrentes de negligência do Usuário na guarda de suas credenciais.",
  "6. CADASTRO DE IMÓVEIS E USO DO MOTOR DE PRECIFICAÇÃO",
  "6.1. O Usuário poderá cadastrar imóveis na Plataforma mediante informação de endereço, características físicas, tipo de imóvel e dados do anúncio em plataformas de hospedagem.",
  "6.2. O Usuário declara que:",
  "I. É proprietário, locatário ou possui autorização legal para anunciar os imóveis cadastrados;",
  "II. Todos os dados informados são verdadeiros, precisos e atualizados;",
  "III. Responde civil e criminalmente pelo cadastro de imóveis sem autorização do proprietário.",
  "6.3. O Motor de IA processa os dados do imóvel cadastrado, dados públicos de mercado (incluindo dados do Airbnb obtidos via API de terceiros) e fatores como sazonalidade, eventos e demanda, gerando Recomendações de Preço para cada imóvel.",
  "6.4. O Usuário poderá definir parâmetros de configuração do motor, como raio de comparação, estratégia de precificação (conservadora, balanceada, agressiva ou IA), limites percentuais de variação e modo de operação (notificação ou automático).",
  "6.5. Os comparáveis utilizados pelo Motor de IA são anonimizados no resultado apresentado ao Usuário. O histórico de aceitação ou rejeição das recomendações pelo Usuário alimenta o processo de aprendizado contínuo do Motor de IA, conforme descrito na Política de Privacidade.",
  "6.6. A Urban AI reserva-se o direito de utilizar dados de precificação agregados e anonimizados, oriundos de múltiplos Usuários, para treino e melhoria do Motor de IA. Esse uso é realizado sobre dados que não identificam individualmente qualquer Usuário, e poderá persistir mesmo após o cancelamento da conta.",
  "7. USO DE INTELIGÊNCIA ARTIFICIAL E TRANSPARÊNCIA ALGORÍTMICA",
  "7.1. A Plataforma utiliza um motor de recomendação proprietário baseado em algoritmo KNN híbrido, treinado com métricas definidas em seu modelo de negócio proprietário.",
  "7.2. As decisões automatizadas de precificação apresentadas pela Plataforma constituem sugestões baseadas em modelos estatísticos e não vinculam o Usuário. Toda aplicação de preço é uma escolha autônoma do Anfitrião, ressalvado o Modo Automático, para o qual o Usuário fornece consentimento expresso e específico.",
  "7.3. O Usuário tem o direito de solicitar revisão humana de qualquer decisão automatizada que lhe diga respeito, nos termos do artigo 20 da LGPD, mediante solicitação ao canal privacidade@myurbanai.com.",
  "7.4. A Urban AI não emite nem transmite ao Usuário qualquer parecer jurídico, fiscal, contábil ou imobiliário. As recomendações geradas pela Plataforma são exclusivamente ferramentas de apoio à decisão de precificação e não substituem a avaliação de profissionais especializados.",
  "7.5. A Urban AI não se responsabiliza por resultados financeiros adversos decorrentes da adoção, pelo Usuário, de Recomendações de Preço geradas pelo Motor de IA, uma vez que o resultado depende de variáveis externas fora do controle da Plataforma.",
  "8. MODO AUTOMÁTICO E INTEGRAÇÃO COM CHANNEL MANAGERS",
  "8.1. O Modo Automático, quando disponível, permite que a Plataforma envie automaticamente preços sugeridos ao canal de distribuição conectado pelo Usuário, mediante:",
  "I. Consentimento explícito, informado e específico do Usuário, mediante aceite em tela própria;",
  "II. Configuração prévia dos parâmetros do motor pelo Usuário;",
  "III. Registro em log auditável de cada aplicação automática de preço (timestamp, imóvel, preço anterior, preço novo, origem IA ou Usuário).",
  "8.2. O Usuário pode revogar a autorização para o Modo Automático a qualquer momento, diretamente pelas configurações da Plataforma. A revogação é imediata e não afeta as aplicações já realizadas.",
  "8.3. A Urban AI não se responsabiliza por erros, falhas ou indisponibilidades dos sistemas de channel managers terceiros que impeçam ou prejudiquem o envio automatizado de preços.",
  "8.4. A integração com canais externos não transfere à Urban AI qualquer responsabilidade pela relação entre o Anfitrião e seus Hóspedes, pela política de reservas, cancelamentos ou estornos de quaisquer plataformas de hospedagem.",
  "9. CONTEÚDO, CONDUTA DOS USUÁRIOS E USOS PROIBIDOS",
  "9.1. O Usuário é exclusivamente responsável por todo o conteúdo que inserir na Plataforma, incluindo dados de imóveis, fotografias, descrições, configurações do motor e quaisquer outras informações.",
  "9.2. A Urban AI não revisa, edita, valida nem aprova o conteúdo inserido pelos Usuários, atuando exclusivamente como fornecedora de infraestrutura tecnológica.",
  "9.3. São expressamente proibidos os seguintes usos da Plataforma:",
  "I. Cadastrar imóveis sem autorização do proprietário ou de quem de direito;",
  "II. Inserir dados falsos, enganosos ou manipulados para distorcer as Recomendações de Preço;",
  "III. Alimentar o Motor de IA com dados fictícios em massa visando a manipulação de resultados ou concorrência desleal;",
  "IV. Compartilhar credenciais de acesso com terceiros não autorizados;",
  "V. Utilizar a Plataforma para fins ilícitos ou em violação à legislação brasileira, incluindo a LGPD, o Código de Defesa do Consumidor, a Lei do Inquilinato e normas municipais sobre hospedagem;",
  "VI. Utilizar dados de outros Usuários eventualmente expostos por erro técnico para fins comerciais ou concorrenciais;",
  "VII. Praticar engenharia reversa, decompilar, clonar, sublicenciar ou criar produto concorrente baseado na tecnologia da Urban AI;",
  "VIII. Enviar spam ou comunicações abusivas a Hóspedes por meio de recursos da Plataforma;",
  "IX. Utilizar robôs, scrapers ou outros mecanismos automatizados para extrair dados da Plataforma sem autorização expressa da Urban AI;",
  "X. Explorar vulnerabilidades de segurança da Plataforma.",
  "9.4. A Urban AI poderá suspender ou encerrar o acesso do Usuário que violar estes Termos, a legislação aplicável ou que adote condutas que gerem risco jurídico, técnico ou reputacional para a Plataforma, com ou sem aviso prévio, conforme a gravidade da infração, nos termos da Cláusula 11.",
  "10. PAGAMENTOS, PLANOS E CANCELAMENTO",
  "10.1. O acesso às funcionalidades completas da Plataforma está condicionado à contratação de Assinatura paga. A cobrança é realizada por imóvel cadastrado, com os seguintes ciclos disponíveis: mensal, trimestral, semestral e anual.",
  "10.2. Os valores vigentes para cada ciclo e quantidade de imóveis são apresentados ao Usuário no momento da contratação, na página de planos disponível em https://myurbanai.com. A Urban AI se reserva o direito de atualizar os valores, com comunicação prévia de no mínimo 30 (trinta) dias por e-mail, conforme disposto na Cláusula 10.7.",
  "10.3. Os pagamentos são processados pela Stripe Brasil, plataforma de pagamentos terceirizada. A Urban AI não armazena dados completos de cartão de crédito, sendo os dados financeiros tratados diretamente pelo processador de pagamentos, em conformidade com o padrão PCI-DSS.",
  "10.4. A Assinatura será renovada automaticamente ao fim de cada ciclo contratado, salvo cancelamento pelo Usuário nos termos da Cláusula 10.6.",
  "10.5. No lançamento da Plataforma, a primeira mensalidade poderá ser isenta, a título de cortesia de boas-vindas, conforme condições vigentes no momento da contratação. Essa isenção não configura promoção ou oferta de teste gratuito e não gera direito adquirido para contratações futuras.",
  "10.6. O Usuário poderá cancelar sua Assinatura a qualquer momento, diretamente pela página \"Meu Plano\" em https://app.myurbanai.com. O cancelamento:",
  "I. Mantém o acesso à Plataforma até o fim do período já pago;",
  "II. Impede a cobrança de novos ciclos;",
  "III. Não enseja reembolso de valores já pagos;",
  "IV. Pode ser revertido durante o período pago remanescente, sem nova cobrança.",
  "10.7. Em caso de falha no pagamento, o sistema realizará até 3 (três) novas tentativas automáticas em até 14 (quatorze) dias. Após esse período, o acesso às funcionalidades poderá ser suspenso. Os dados serão preservados conforme a política de retenção descrita na Política de Privacidade.",
  "10.8. Para planos anuais ou semestrais cancelados fora do período de arrependimento, não haverá reembolso proporcional dos valores já pagos, salvo disposição contratual expressa em contrário.",
  "10.9. Os preços contratados pelo Usuário são preservados durante o ciclo vigente. Ao término do ciclo, o Usuário poderá contratar o próximo ciclo pelo preço vigente na ocasião. Eventuais reajustes serão comunicados com antecedência mínima de 30 (trinta) dias.",
  "11. SUSPENSÃO E ENCERRAMENTO DE CONTA",
  "11.1. A Urban AI poderá suspender temporariamente ou encerrar definitivamente o acesso do Usuário à Plataforma nas seguintes hipóteses:",
  "I. Violação destes Termos ou da Política de Privacidade;",
  "II. Descumprimento da legislação brasileira aplicável;",
  "III. Inadimplência, após aviso prévio e período de tolerância de 7 (sete) dias contados do vencimento;",
  "IV. Suspeita fundada de fraude, lavagem de dinheiro ou atividades ilícitas;",
  "V. Uso abusivo de recursos da Plataforma que comprometa sua disponibilidade ou integridade;",
  "VI. Risco jurídico ou reputacional relevante para a Urban AI decorrente da conduta do Usuário.",
  "11.2. Nas hipóteses de infração grave (fraude, atividade ilícita ou tentativa de comprometimento da segurança da Plataforma), a suspensão poderá ser imediata, independentemente de notificação prévia.",
  "11.3. Nas demais hipóteses, a Urban AI enviará notificação ao Usuário com prazo razoável para regularização antes do encerramento definitivo da conta.",
  "11.4. O Usuário poderá solicitar o encerramento de sua própria conta a qualquer momento, mediante solicitação ao e-mail privacidade@myurbanai.com. O encerramento implica a cessação do acesso à Plataforma e o tratamento dos dados conforme a Política de Privacidade.",
  "11.5. Após o encerramento da conta, o Usuário dispõe de prazo de até 30 (trinta) dias para exportar seus dados da Plataforma, antes que seja realizada a remoção ou anonimização dos dados pessoais identificáveis, nos termos da Política de Privacidade. Dados fiscais serão retidos pelo prazo legalmente exigido.",
  "12. PROPRIEDADE INTELECTUAL",
  "12.1. A Plataforma Urban AI, incluindo código-fonte, Motor de IA, arquitetura de software, banco de dados, interfaces, design, logotipos, marca \"Urban AI\" e demais elementos de identidade visual, são de propriedade exclusiva da MP IA Tecnologia Ltda, protegidos nos termos da Lei nº 9.610/1998 (Lei de Direitos Autorais), da Lei nº 9.279/1996 (Lei de Propriedade Industrial) e demais normas aplicáveis.",
  "12.2. O Usuário recebe, pelo prazo da Assinatura, uma licença de uso limitada, não exclusiva, intransferível e revogável para utilização da Plataforma exclusivamente para a finalidade de precificação de seus imóveis para aluguel por temporada, em conformidade com estes Termos.",
  "12.3. São expressamente vedados ao Usuário:",
  "I. Reproduzir, copiar, clonar, modificar, distribuir ou sublicenciar qualquer componente da Plataforma;",
  "II. Praticar engenharia reversa, descompilação ou desmontagem da Plataforma ou do Motor de IA;",
  "III. Utilizar código, telas, identidade visual ou qualquer elemento da Plataforma para construir produto ou serviço concorrente;",
  "IV. Revender o acesso à Plataforma a terceiros sem autorização expressa da Urban AI.",
  "12.4. Os dados dos imóveis, fotografias e demais conteúdos inseridos pelo Usuário permanecem de sua propriedade. O Usuário concede à Urban AI licença não exclusiva, mundial, gratuita e pelo prazo da relação contratual para tratar esses dados com a finalidade de prestar os serviços contratados.",
  "12.5. A Urban AI é titular dos modelos treinados, embeddings, snapshots agregados e datasets anonimizados gerados a partir dos dados de múltiplos Usuários. O Usuário não adquire qualquer direito sobre o modelo de IA ou sobre datasets agregados, tendo direito exclusivamente sobre seus próprios dados, nos termos da Política de Privacidade.",
  "12.6. Os dados públicos de mercado consumidos pela Plataforma (incluindo dados públicos do Airbnb obtidos por meio de API de terceiros e dados de eventos obtidos por scraping de fontes públicas) são utilizados exclusivamente como insumo para o Motor de IA, dentro dos limites dos termos de uso dos respectivos fornecedores.",
  "13. PROTEÇÃO DE DADOS PESSOAIS (LGPD)",
  "13.1. A Urban AI trata os dados pessoais dos Usuários em conformidade com a Lei nº 13.709/2018 (LGPD), adotando as medidas técnicas e administrativas necessárias à proteção dos dados pessoais contra acessos não autorizados, situações acidentais ou ilícitas de destruição, perda, alteração, comunicação ou difusão.",
  "13.2. A MP IA Tecnologia Ltda atua como Controladora dos dados pessoais dos Usuários. A Guilds (Operadora Técnica), a Stripe Brasil, a Brevo, a RapidAPI, a Railway, a AWS, o Sentry e demais prestadores listados na Política de Privacidade atuam como operadores ou suboperadores, processando dados em nome da Controladora e sob suas instruções.",
  "13.3. Os principais dados pessoais tratados incluem: nome completo, e-mail, telefone (opcional), dados da empresa (opcional), endereço dos imóveis, dados de autenticação, informações de pagamento (processadas diretamente pelo Stripe) e logs de acesso.",
  "13.4. Os dados pessoais dos Usuários são tratados com as seguintes finalidades e bases legais:",
  "I. Autenticação e acesso à Plataforma para execução do contrato (art. 7º, V, LGPD);",
  "II. Prestação dos serviços de precificação para execução do contrato (art. 7º, V, LGPD);",
  "III. Cobrança recorrente da Assinatura para execução do contrato e cumprimento de obrigação legal (art. 7º, V e II, LGPD);",
  "IV. Retenção fiscal de pagamentos, como cumprimento de obrigação legal (art. 7º, II, LGPD);",
  "V. Envio de e-mails transacionais para execução de contrato (art. 7º, V, LGPD);",
  "VI. Envio de push automático de preços, mediante consentimento explícito (art. 7º, I, LGPD);",
  "VII. Logs de IP e agente-usuário para segurança, atendendo ao legítimo interesse (art. 7º, IX, LGPD);",
  "VIII. Analytics de uso, mediante consentimento (art. 7º, I, LGPD), obtido pelo aceite do banner de cookies;",
  "IX. Melhoria do Motor de IA com dados anonimizados, com base no legítimo interesse (art. 7º, IX, LGPD).",
  "13.5. O Usuário, na qualidade de titular de dados pessoais, pode exercer os seguintes direitos perante a Urban AI, nos termos do artigo 18 da LGPD:",
  "I. Acesso aos dados pessoais tratados;",
  "II. Correção de dados incompletos, inexatos ou desatualizados;",
  "III. Anonimização, bloqueio ou eliminação de dados desnecessários ou tratados em desconformidade;",
  "IV. Portabilidade dos dados em formato estruturado;",
  "V. Eliminação dos dados tratados com base em consentimento;",
  "VI. Revogação do consentimento a qualquer tempo;",
  "VII. Oposição ao tratamento baseado em legítimo interesse;",
  "VIII. Informação sobre os compartilhamentos de dados realizados com terceiros;",
  "IX. Revisão de decisões tomadas com base em tratamento automatizado, nos termos do art. 20 da LGPD;",
  "X. Apresentação de reclamação à Autoridade Nacional de Proteção de Dados (ANPD).",
  "13.6. As solicitações relativas aos direitos do titular devem ser encaminhadas ao canal oficial de privacidade: privacidade@myurbanai.com. A Urban AI compromete-se a responder no prazo de 15 (quinze) dias corridos, nos termos do artigo 19 da LGPD.",
  "13.7. Em razão do uso de provedores de infraestrutura localizados fora do Brasil (Railway, Brevo, Stripe parcial, Sentry, Google Cloud, entre outros), poderá ocorrer transferência internacional de dados pessoais. Tais transferências são realizadas com provedores que adotam garantias contratuais adequadas, nos termos dos artigos 33 a 36 da LGPD.",
  "13.8. A Urban AI adotará medidas técnicas e organizacionais para detectar e responder a incidentes de segurança. Em caso de incidente com risco relevante ao Usuário, a Urban AI notificará a ANPD no prazo de 72 (setenta e duas) horas e comunicará os titulares afetados, nos termos do artigo 48 da LGPD.",
  "13.9. Para informações detalhadas sobre as práticas de privacidade, operadores envolvidos, prazos de retenção, uso de cookies e demais aspectos do tratamento de dados, consulte a Política de Privacidade em https://myurbanai.com/privacidade.",
  "14. COOKIES E RASTREADORES",
  "14.1. A Plataforma utiliza cookies e tecnologias similares para fins técnicos, analíticos e de marketing, conforme descrito abaixo:",
  "I. Cookies essenciais (sempre ativos): necessários para autenticação, segurança da sessão e funcionamento básico da Plataforma. Incluem cookie de autenticação, refresh-token e cookie CSRF;",
  "II. Cookies analíticos (com consentimento): com anonimização de IP ativa, para análise de uso da Plataforma. Ativados somente após aceite expresso pelo Usuário;",
  "III. Cookies de marketing (com consentimento): para análise de conversão de campanhas. Ativados somente após aceite expresso pelo Usuário.",
  "14.2. No primeiro acesso, o Usuário será informado sobre os cookies utilizados e poderá escolher quais categorias aceita, por meio do banner de consentimento. O consentimento para cookies analíticos e de marketing é voluntário e revogável a qualquer tempo nas configurações da Plataforma.",
  "14.3. Para informações detalhadas sobre os cookies utilizados, consulte a Política de Privacidade.",
  "15. DISPONIBILIDADE, MANUTENÇÕES E ATUALIZAÇÕES",
  "15.1. A Urban AI envidará seus melhores esforços para manter a Plataforma disponível de forma contínua. Entretanto, não garante disponibilidade ininterrupta, podendo ocorrer interrupções por:",
  "I. Manutenções programadas, anunciadas com antecedência razoável;",
  "II. Falhas de infraestrutura de terceiros (provedores de cloud, processadores de pagamento, APIs externas);",
  "III. Eventos de força maior ou caso fortuito;",
  "IV. Ataques cibernéticos ou eventos de segurança.",
  "15.2. A Urban AI poderá atualizar, modificar, adicionar ou remover funcionalidades da Plataforma a qualquer tempo, sem obrigação de aviso prévio para atualizações de menor impacto. Alterações substanciais serão comunicadas com antecedência razoável.",
  "15.3. A Urban AI não se responsabiliza por danos decorrentes de interrupções ou indisponibilidades da Plataforma que não decorram de dolo ou culpa grave de sua parte.",
  "16. LIMITAÇÃO DE RESPONSABILIDADE",
  "16.1. A Urban AI não se responsabiliza por:",
  "I. Resultado financeiro, ocupação ou rentabilidade do Usuário decorrente do uso ou não das Recomendações de Preço;",
  "II. Decisões de precificação adotadas pelo Usuário com base nas recomendações da Plataforma;",
  "III. Indisponibilidade, alteração ou descontinuidade de canais de distribuição terceiros (Airbnb, Stays e similares) que impactem a operação do Usuário;",
  "IV. Conteúdo inserido pelo Usuário na Plataforma, incluindo dados inverídicos ou errôneos;",
  "V. Condutas de terceiros integradores ou parceiros comerciais do Usuário;",
  "VI. Perdas indiretas, lucros cessantes, dano emergente não previsto ou dano moral, salvo em caso de dolo ou culpa grave comprovada da Urban AI;",
  "VII. Alterações nos termos de serviço de plataformas terceiras que afetem a integração com a Urban AI.",
  "16.2. Em nenhuma hipótese a responsabilidade total da Urban AI perante o Usuário, decorrente de qualquer causa relacionada a estes Termos, excederá o valor equivalente às mensalidades efetivamente pagas pelo Usuário nos últimos 12 (doze) meses anteriores ao evento danoso, ressalvadas as hipóteses de dolo ou culpa grave.",
  "16.3. O Usuário concorda que as limitações de responsabilidade previstas nesta Cláusula refletem uma alocação razoável de riscos entre as partes e constituem condição essencial do modelo de precificação adotado pela Urban AI.",
  "17. COMUNICAÇÕES E NOTIFICAÇÕES",
  "17.1. A Urban AI comunicar-se-á com o Usuário por meio do endereço de e-mail cadastrado na conta, pelos seguintes canais:",
  "I. E-mail transacional: notificações sobre a conta, assinatura, alertas de quota e comunicados sobre incidentes ou alterações destes Termos;",
  "II. Assistente in-app: atendimento de primeira linha e suporte à navegação;",
  "III. E-mail comercial: suporte@myurbanai.com;",
  "IV. Canal de privacidade: privacidade@myurbanai.com.",
  "17.2. Comunicações de marketing e newsletter, quando disponibilizadas, exigirão consentimento expresso e separado do Usuário, com opção de cancelamento a qualquer momento.",
  "17.3. O Usuário é responsável por manter seu endereço de e-mail atualizado. Notificações enviadas ao e-mail cadastrado serão consideradas recebidas, independentemente de leitura efetiva.",
  "18. ALTERAÇÕES DOS TERMOS",
  "18.1. A Urban AI poderá modificar estes Termos a qualquer tempo, mediante publicação da versão atualizada na Plataforma, com indicação da data da última atualização.",
  "18.2. Para alterações materiais que impactem direitos ou obrigações relevantes do Usuário, a Urban AI comunicará o Usuário com antecedência de no mínimo 30 (trinta) dias por e-mail, indicando as principais mudanças.",
  "18.3. A continuidade do uso da Plataforma após o prazo de comunicação implica aceitação da versão atualizada dos Termos. Caso o Usuário não concorde com as alterações, poderá cancelar sua Assinatura nos termos da Cláusula 10.6, sem pagamento de penalidade.",
  "19. DISPOSIÇÕES GERAIS",
  "19.1. A tolerância da Urban AI quanto a qualquer descumprimento destes Termos pelo Usuário não implica novação, renúncia ou alteração das obrigações contratualmente estabelecidas.",
  "19.2. A nulidade ou ineficácia de qualquer disposição destes Termos não afetará a validade e eficácia das demais, que permanecerão em plena vigência.",
  "19.3. Estes Termos não criam qualquer relação de emprego, parceria, representação, agência ou sociedade entre as partes.",
  "19.4. O Usuário não poderá ceder ou transferir seus direitos e obrigações decorrentes destes Termos sem prévia autorização escrita da Urban AI.",
  "19.5. Estes Termos constituem o acordo integral entre as partes relativamente ao uso da Plataforma, substituindo quaisquer entendimentos ou negociações anteriores sobre o mesmo objeto.",
  "19.6. A Plataforma não se destina ao uso por Hóspedes dos Anfitriões. A Urban AI não mantém relação contratual ou comunicação direta com Hóspedes em nenhuma circunstância.",
  "20. LEGISLAÇÃO APLICÁVEL E FORO",
  "20.1. Estes Termos são regidos pelas leis da República Federativa do Brasil, em especial o Código Civil (Lei nº 10.406/2002), o Marco Civil da Internet (Lei nº 12.965/2014), o Código de Defesa do Consumidor (Lei nº 8.078/1990), quando aplicável, e a Lei Geral de Proteção de Dados Pessoais (Lei nº 13.709/2018).",
  "20.2. Fica eleito o Foro da Comarca de Barueri/SP para dirimir quaisquer litígios ou controvérsias decorrentes ou relacionados a estes Termos, com renúncia a qualquer outro, por mais privilegiado que seja, salvo nas hipóteses em que o Usuário se qualificar como consumidor, hipótese em que prevalece o foro de seu domicílio nos termos do artigo 101, I do Código de Defesa do Consumidor.",
  "São Paulo, 11 de maio de 2026.",
  "MP IA Tecnologia Ltda",
  "Urban AI",
  "CNPJ 62.497.936/0001-27"
] as const;

export const privacyBlocks = toBlocks([...privacyItems]);
export const termsBlocks = toBlocks([...termsItems]);
