networks:
  app_network:
    driver: bridge

services:
  pipeline-orchestrator:
    image: prefecthq/prefect:3-python3.12
    command: prefect server start --host 0.0.0.0
    ports:
      - 4200:4200
    restart: "no"
    networks:
      - app_network
    depends_on:
      web-scrapping-api:
        condition: service_healthy

  web-scrapping-api:
    image: web-scrapper:latest
    build:
      context: .
    ports:
      - 9080:9080
    healthcheck:
      test: ["CMD", "ls", "/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    networks:
      - app_network