name: Mirror to GitLab

on:
  push:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Fetch all branches
        run: git fetch --all
      - name: Push to GitLab
        run: |
          git remote add gitlab "https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.luminalab.ai/guillerme/urban-webscraping.git"
          git config http.sslVerify false
          git push gitlab --all --force
          git push gitlab --tags --force
