import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * DR-1 — CatchupCoreEntities.
 *
 * As 11 tabelas core do negócio (user, addresses, list, events, plans, payment,
 * process_status, analise_preco, analise_endereco_evento, email_confirmations,
 * notifications) NÃO tinham CREATE TABLE em nenhuma migration — o schema de prod
 * veio de `synchronize: true` histórico e o Baseline é no-op. Consequência: um
 * banco reconstruído do zero rodava `migration:run` com exit 0 mas sem nenhuma
 * dessas tabelas (falha silenciosa) — inviabilizando disaster recovery.
 *
 * Esta migration cria as 11 tabelas (DDL derivado de `migration:generate` contra
 * um banco vazio, curado para remover o ruído de drift das outras tabelas).
 * Idempotente: gate em hasTable('user') — no-op em prod, cria tudo no zero.
 *
 * Placement: timestamp alto (roda depois que todas as outras tabelas já existem),
 * então os FKs "existentes -> core" podem ser adicionados aqui.
 *
 * GERADO E TESTADO contra MySQL 8 vazio em 2026-07-06 (drop DB -> migration:run ->
 * 11 tabelas presentes -> migration:generate subsequente sem CREATE TABLE).
 */
export class CatchupCoreEntities1783400000000 implements MigrationInterface {
  name = 'CatchupCoreEntities1783400000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
        // Gate idempotente: em prod (schema completo via synchronize histórico)
        // a tabela `user` existe -> nada a fazer. Em banco reconstruído do zero,
        // as 11 tabelas core não existem -> cria todas + índices + FKs.
        const hasCore = await queryRunner.hasTable('user');
        if (hasCore) return;

        // --- CREATE TABLE (11 tabelas core) ---
        await queryRunner.query(`CREATE TABLE \`notifications\` (\`id\` varchar(36) NOT NULL, \`title\` varchar(255) NOT NULL, \`description\` text NULL, \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`title_button\` varchar(255) NULL, \`redirect_to\` varchar(255) NULL, \`sent\` tinyint NOT NULL DEFAULT 0, \`opened\` tinyint NOT NULL DEFAULT 0, \`send_email\` tinyint NOT NULL DEFAULT 0, \`user_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user\` (\`id\` varchar(36) NOT NULL, \`username\` varchar(255) NOT NULL, \`email\` varchar(255) NOT NULL, \`password\` varchar(255) NOT NULL, \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`distance_km\` double NULL DEFAULT '30', \`ativo\` tinyint NOT NULL DEFAULT 1, \`phone\` varchar(255) NULL, \`company\` varchar(255) NULL, \`pricingStrategy\` varchar(255) NULL DEFAULT 'conservative', \`operationMode\` varchar(255) NULL DEFAULT 'notifications', \`percentualInicial\` decimal(5,2) NULL, \`percentualFinal\` decimal(5,2) NULL, \`airbnbHostId\` varchar(255) NULL, \`role\` varchar(16) NOT NULL DEFAULT 'host', \`onboardingDripLastDay\` int NULL, \`onboardingDripLastSentAt\` timestamp NULL, UNIQUE INDEX \`IDX_e12875dfb3b1d92d7d7c5377e2\` (\`email\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`list\` (\`id\` varchar(36) NOT NULL, \`titulo\` varchar(255) NOT NULL, \`id_do_anuncio\` varchar(255) NOT NULL, \`internalNickname\` varchar(80) NULL, \`internalCode\` varchar(32) NULL, \`picture_url\` varchar(255) NULL, \`ativo\` tinyint NOT NULL DEFAULT 1, \`priceText\` varchar(255) NULL, \`raw\` float NULL, \`currency\` varchar(255) NULL, \`checkIn\` date NULL, \`checkOut\` date NULL, \`status\` varchar(255) NULL, \`dailyPrice\` float NULL, \`manualDailyPrice\` float NULL, \`averageMonthlyRevenue\` float NULL, \`pricingInputSource\` varchar(255) NULL, \`pricingInputsUpdatedAt\` timestamp NULL, \`hospedes\` int NULL, \`quartos\` int NULL, \`camas\` int NULL, \`banheiros\` int NULL, \`rating\` float NULL, \`propertyType\` varchar(255) NULL, \`amenitiesCount\` int NULL, \`neighborhood\` varchar(255) NULL, \`reviewCount\` int NULL, \`lastScrapedAt\` timestamp NULL, \`user_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`process_status\` (\`id\` varchar(36) NOT NULL, \`status\` enum ('running', 'completed', 'error') NOT NULL DEFAULT 'completed', \`errorMessage\` text NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`addresses\` (\`id\` varchar(36) NOT NULL, \`cep\` varchar(9) NOT NULL, \`numero\` varchar(20) NOT NULL, \`logradouro\` varchar(255) NULL, \`bairro\` varchar(255) NULL, \`cidade\` varchar(255) NULL, \`estado\` varchar(2) NULL, \`latitude\` decimal(10,8) NULL, \`longitude\` decimal(11,8) NULL, \`ativo\` tinyint NOT NULL DEFAULT 1, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`analisado\` varchar(255) NOT NULL DEFAULT 'pending', \`idAlertAirb\` varchar(255) NOT NULL DEFAULT 'no_id', \`list_id\` varchar(36) NULL, \`user_id\` varchar(36) NULL, INDEX \`IDX_41aa769237c813f7ffebd0b26c\` (\`cep\`), INDEX \`IDX_645885a28d9d34ba539fdda6a8\` (\`cidade\`), INDEX \`IDX_ef4dab2d4e8cbfa5b9067c275d\` (\`list_id\`, \`user_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`events\` (\`id\` varchar(36) NOT NULL, \`nome\` varchar(255) NOT NULL, \`descricao\` text NULL, \`dataInicio\` datetime NOT NULL, \`dataFim\` datetime NOT NULL, \`enderecoCompleto\` text NOT NULL, \`cidade\` varchar(255) NOT NULL, \`estado\` varchar(2) NOT NULL, \`latitude\` decimal(10,8) NULL, \`longitude\` decimal(11,8) NULL, \`linkSiteOficial\` text NULL, \`imagem_url\` text NULL, \`categoria\` varchar(100) NULL, \`relevancia\` int NULL, \`raioImpactoKm\` decimal(5,2) NULL, \`capacidadeEstimada\` int NULL, \`source\` varchar(64) NULL, \`sourceId\` varchar(128) NULL, \`dedupHash\` varchar(64) NULL, \`venueCapacity\` int NULL, \`venueType\` varchar(64) NULL, \`expectedAttendance\` int NULL, \`crawledUrl\` text NULL, \`canonicalName\` varchar(255) NULL, \`normalizedName\` varchar(255) NULL, \`normalizedVenue\` varchar(255) NULL, \`canonicalVenueId\` varchar(36) NULL, \`duplicateOfEventId\` varchar(36) NULL, \`dedupStatus\` varchar(16) NOT NULL DEFAULT 'canonical', \`identityConfidence\` decimal(5,4) NULL, \`sourceCount\` int NOT NULL DEFAULT '0', \`lastSeenAt\` datetime NULL, \`pendingGeocode\` tinyint NOT NULL DEFAULT 0, \`outOfScope\` tinyint NOT NULL DEFAULT 0, \`enrichmentAttempts\` int NOT NULL DEFAULT '0', \`enrichmentLastAttemptAt\` datetime NULL, \`enrichmentLastError\` varchar(500) NULL, \`ativo\` tinyint NOT NULL DEFAULT 1, \`dataCrawl\` timestamp NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_67108534254a58377f0b6b8fe8\` (\`nome\`), INDEX \`IDX_e50b15278a3b66d693d8dad0f6\` (\`dataInicio\`), INDEX \`IDX_09d898cc65715a8b22d7097cf1\` (\`dataFim\`), INDEX \`IDX_da09dd22804c5ab5d5c193df44\` (\`cidade\`), INDEX \`IDX_04c6ba002d34db794ef453aadd\` (\`estado\`), INDEX \`IDX_f002d2d980327cc1c4c4e368f6\` (\`latitude\`), INDEX \`IDX_2842db70f335693a76e656ae0d\` (\`longitude\`), INDEX \`IDX_204faf0c2a181c459e7ce9f4c5\` (\`categoria\`), INDEX \`IDX_cb1b45b0a16c1b5c5a685aec5b\` (\`source\`), INDEX \`IDX_144c41631f2a25ccd964f2d628\` (\`pendingGeocode\`), INDEX \`IDX_b2b78677ca545a1f9906bb7dc8\` (\`outOfScope\`), INDEX \`IDX_abf1d6218c3e7ffe52e54ca211\` (\`enrichmentLastAttemptAt\`), INDEX \`IDX_f0cd9c1f64dd1484474fd9ed61\` (\`dataCrawl\`), INDEX \`IDX_events_cidade_estado_outOfScope\` (\`cidade\`, \`estado\`, \`outOfScope\`), INDEX \`IDX_events_geo_dataInicio\` (\`latitude\`, \`longitude\`, \`dataInicio\`), INDEX \`IDX_events_dataInicio_outOfScope\` (\`dataInicio\`, \`outOfScope\`), INDEX \`IDX_1d223cd230667e7d2614e26e4c\` (\`venueType\`), INDEX \`IDX_15acf739592c0f48f7056735aa\` (\`dataInicio\`, \`dataFim\`), INDEX \`IDX_58095308749008e0a54eabf0ff\` (\`latitude\`, \`longitude\`), INDEX \`IDX_3a56c148d67440d4a749a384e5\` (\`cidade\`, \`estado\`), UNIQUE INDEX \`IDX_d10a5393425b5c2dd1c5e95be5\` (\`dedupHash\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`analise_preco\` (\`id\` varchar(36) NOT NULL, \`distancia_sua_propriedade\` float NOT NULL, \`distancia_propriedade_referencia\` float NOT NULL, \`preco_sugerido\` decimal(10,2) NOT NULL, \`seu_preco_atual\` decimal(10,2) NOT NULL, \`diferenca_percentual\` decimal(5,2) NOT NULL, \`recomendacao\` varchar(255) NOT NULL, \`aceito\` tinyint NOT NULL DEFAULT 0, \`status\` varchar(24) NOT NULL DEFAULT 'suggested', \`aceito_em\` timestamp NULL, \`rejeitado_em\` timestamp NULL, \`expirado_em\` timestamp NULL, \`preco_aplicado\` decimal(10,2) NULL, \`aplicado_em\` timestamp NULL, \`origem_aplicacao\` varchar(32) NULL, \`reserva_status\` varchar(24) NULL, \`receita_real\` decimal(10,2) NULL, \`noites_reservadas\` int NULL, \`resultado_registrado_em\` timestamp NULL, \`feedback_observacao\` text NULL, \`verification_status\` varchar(24) NULL, \`verification_checked_at\` timestamp NULL, \`verified_applied_at\` timestamp NULL, \`observed_price\` decimal(10,2) NULL, \`verification_source\` varchar(48) NULL, \`verification_error\` text NULL, \`motivo_ia\` text NULL, \`criado_em\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`endereco_id\` varchar(36) NOT NULL, \`evento_id\` varchar(36) NOT NULL, \`usuario_proprietario_id\` varchar(36) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`payment\` (\`id\` varchar(36) NOT NULL, \`status\` varchar(20) NOT NULL DEFAULT 'pending', \`expireDate\` timestamp NULL, \`startDate\` timestamp NULL, \`customerId\` varchar(255) NULL, \`subscriptionId\` varchar(255) NULL, \`mode\` varchar(50) NULL, \`billingCycle\` varchar(32) NULL, \`listingsContratados\` int NULL DEFAULT '1', \`planName\` varchar(64) NULL, \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`user_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`plans\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`title\` varchar(255) NOT NULL, \`price\` varchar(255) NULL, \`priceAnnual\` varchar(255) NULL, \`originalPrice\` varchar(255) NULL, \`originalPriceAnnual\` varchar(255) NULL, \`stripePriceId\` varchar(255) NULL, \`stripePriceIdAnnual\` varchar(255) NULL, \`priceMonthly\` varchar(255) NULL, \`priceQuarterly\` varchar(255) NULL, \`priceSemestral\` varchar(255) NULL, \`priceAnnualNew\` varchar(255) NULL, \`originalPriceMonthly\` varchar(255) NULL, \`originalPriceQuarterly\` varchar(255) NULL, \`originalPriceSemestral\` varchar(255) NULL, \`originalPriceAnnualNew\` varchar(255) NULL, \`stripePriceIdMonthly\` varchar(255) NULL, \`stripePriceIdQuarterly\` varchar(255) NULL, \`stripePriceIdSemestral\` varchar(255) NULL, \`stripePriceIdAnnualNew\` varchar(255) NULL, \`discountQuarterlyPercent\` int NULL, \`discountSemestralPercent\` int NULL, \`discountAnnualPercent\` int NULL, \`discountBadge\` varchar(255) NULL, \`highlightBadge\` varchar(255) NULL, \`period\` varchar(255) NULL, \`features\` text NOT NULL, \`propertyLimit\` int NULL, \`minProperties\` int NULL, \`maxProperties\` int NULL, \`maxCheckoutQuantity\` int NULL, \`selfServiceEnabled\` tinyint NOT NULL DEFAULT 1, \`sortOrder\` int NOT NULL DEFAULT '0', \`isCustomPrice\` tinyint NOT NULL DEFAULT 0, \`isActive\` tinyint NOT NULL DEFAULT 1, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_253d25dae4c94ee913bc5ec485\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`analise_endereco_evento\` (\`id\` varchar(36) NOT NULL, \`distancia_metros\` int NOT NULL, \`duração_minutos\` int NOT NULL, \`transport_mode\` varchar(50) NOT NULL, \`enviado\` tinyint NOT NULL, \`criado_em\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`atualizado_em\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`evento_id\` varchar(36) NOT NULL, \`endereco_id\` varchar(36) NOT NULL, \`usuario_proprietario_id\` varchar(36) NOT NULL, INDEX \`IDX_ad8af3fbf1b0c92ae855c42ae4\` (\`evento_id\`, \`endereco_id\`, \`usuario_proprietario_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`email_confirmations\` (\`id\` varchar(36) NOT NULL, \`code\` varchar(255) NOT NULL, \`expiresAt\` datetime NOT NULL, \`confirmed\` tinyint NOT NULL DEFAULT 0, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`userId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);

        // --- índices das tabelas core ---

        // --- foreign keys (core<->core e existentes->core) ---
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD CONSTRAINT \`FK_9a8a82462cab47c73d25f49261f\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`stays_accounts\` ADD CONSTRAINT \`FK_3e7fc514d8924977dbb7f924f2a\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`list\` ADD CONSTRAINT \`FK_a842f768ec87a346b0ee61fabba\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`stays_listings\` ADD CONSTRAINT \`FK_40f1c080af17930153ff6846a4e\` FOREIGN KEY (\`propriedade_id\`) REFERENCES \`list\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_communication_preferences\` ADD CONSTRAINT \`FK_a453511f538784d3ba976138276\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`refresh_tokens\` ADD CONSTRAINT \`FK_610102b60fea1455310ccd299de\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`push_subscriptions\` ADD CONSTRAINT \`FK_6771f119f1c06d2ccf38f238664\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`push_deliveries\` ADD CONSTRAINT \`FK_43155f860140c479ce7997e5c5f\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`addresses\` ADD CONSTRAINT \`FK_7680f3c6138b45c8f793258820b\` FOREIGN KEY (\`list_id\`) REFERENCES \`list\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`addresses\` ADD CONSTRAINT \`FK_16aac8a9f6f9c1dd6bcb75ec023\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pricing_rule_configs\` ADD CONSTRAINT \`FK_a0c9f554f7363af08369eab78f7\` FOREIGN KEY (\`address_id\`) REFERENCES \`addresses\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pricing_rule_configs\` ADD CONSTRAINT \`FK_f8e9afe3eefe5e4493f2c04d1e5\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pricing_recommendation_digests\` ADD CONSTRAINT \`FK_244edf445120adcf56709dfc6b2\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`analise_preco\` ADD CONSTRAINT \`FK_4ed2f899f51045514270b4f41df\` FOREIGN KEY (\`endereco_id\`) REFERENCES \`addresses\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`analise_preco\` ADD CONSTRAINT \`FK_a434e6fd22a6d010eded859f735\` FOREIGN KEY (\`evento_id\`) REFERENCES \`events\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`analise_preco\` ADD CONSTRAINT \`FK_8c79ec3e52d989c410e0fe6fc2b\` FOREIGN KEY (\`usuario_proprietario_id\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`event_intelligence_snapshots\` ADD CONSTRAINT \`FK_394f9c8251bb23418fa59b4d61f\` FOREIGN KEY (\`event_id\`) REFERENCES \`events\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`event_property_impacts\` ADD CONSTRAINT \`FK_42f43179d6c8b1ddfeed3731875\` FOREIGN KEY (\`event_id\`) REFERENCES \`events\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`event_property_impacts\` ADD CONSTRAINT \`FK_5b94659ffae5b505a8ae1af9a63\` FOREIGN KEY (\`property_address_id\`) REFERENCES \`addresses\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`event_property_impacts\` ADD CONSTRAINT \`FK_388cf11b5919d091da3ad94530d\` FOREIGN KEY (\`list_id\`) REFERENCES \`list\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`event_property_impacts\` ADD CONSTRAINT \`FK_ba74a9815d867339ad625d311ba\` FOREIGN KEY (\`host_user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`event_property_impacts\` ADD CONSTRAINT \`FK_9ff961a23b4b81376170ebaa9f1\` FOREIGN KEY (\`analise_preco_id\`) REFERENCES \`analise_preco\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`price_updates\` ADD CONSTRAINT \`FK_c4fbd15114a898d18e8b90d3dda\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`price_updates\` ADD CONSTRAINT \`FK_ef31c0de68527eddace1c983a77\` FOREIGN KEY (\`analise_preco_id\`) REFERENCES \`analise_preco\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pricing_decision_snapshots\` ADD CONSTRAINT \`FK_83b2b9147c22758a9829db76a9d\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pricing_decision_snapshots\` ADD CONSTRAINT \`FK_3ff818e047d7fb432bfc8ad72d1\` FOREIGN KEY (\`property_address_id\`) REFERENCES \`addresses\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pricing_decision_snapshots\` ADD CONSTRAINT \`FK_cc14316986a462433b7011b300a\` FOREIGN KEY (\`list_id\`) REFERENCES \`list\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pricing_decision_snapshots\` ADD CONSTRAINT \`FK_f6e9e120b923470f3dfbd812192\` FOREIGN KEY (\`event_id\`) REFERENCES \`events\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pricing_decision_snapshots\` ADD CONSTRAINT \`FK_b5b16e6182e3ae696d4410e5865\` FOREIGN KEY (\`analise_preco_id\`) REFERENCES \`analise_preco\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`price_snapshots\` ADD CONSTRAINT \`FK_e65a0e31ccfdf51a753023a12cc\` FOREIGN KEY (\`list_id\`) REFERENCES \`list\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`price_snapshots\` ADD CONSTRAINT \`FK_79c0df5bd89539c96233e488772\` FOREIGN KEY (\`address_id\`) REFERENCES \`addresses\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pricing_input_history\` ADD CONSTRAINT \`FK_a4fbeab7966206100edd4a51ce6\` FOREIGN KEY (\`list_id\`) REFERENCES \`list\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pricing_input_history\` ADD CONSTRAINT \`FK_d1949219fe66290784f716bdb95\` FOREIGN KEY (\`address_id\`) REFERENCES \`addresses\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pricing_input_history\` ADD CONSTRAINT \`FK_132ae0001aa1893a97c218fe0db\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`portfolio_property_settings\` ADD CONSTRAINT \`FK_2dd78fba1f54c092585c87441e1\` FOREIGN KEY (\`address_id\`) REFERENCES \`addresses\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`portfolio_property_settings\` ADD CONSTRAINT \`FK_279d28cd294a69a027b7c616dbe\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`portfolio_action_items\` ADD CONSTRAINT \`FK_245e66ca27639fce98ee5f3483e\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`portfolio_action_items\` ADD CONSTRAINT \`FK_363697df67568d6822abf553e52\` FOREIGN KEY (\`address_id\`) REFERENCES \`addresses\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`portfolio_action_runs\` ADD CONSTRAINT \`FK_e7b34ced15aa4938b7aad241611\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`portfolio_daily_price_overrides\` ADD CONSTRAINT \`FK_fceb3dbac23e59a4b31ccd1a89e\` FOREIGN KEY (\`address_id\`) REFERENCES \`addresses\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`portfolio_daily_price_overrides\` ADD CONSTRAINT \`FK_0cb6a1855e1e8a44956c71490de\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payment\` ADD CONSTRAINT \`FK_c66c60a17b56ec882fcd8ec770b\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`occupancy_history\` ADD CONSTRAINT \`FK_cd82c8cd8dfb346b8fa6371ec9a\` FOREIGN KEY (\`list_id\`) REFERENCES \`list\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`occupancy_history\` ADD CONSTRAINT \`FK_4a78620d1a9263a3b8804215191\` FOREIGN KEY (\`address_id\`) REFERENCES \`addresses\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`occupancy_history\` ADD CONSTRAINT \`FK_f1e2f99e0988d336ffd363627ea\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`password_reset_tokens\` ADD CONSTRAINT \`FK_52ac39dd8a28730c63aeb428c9c\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`event_sources\` ADD CONSTRAINT \`FK_9fcead4b70498e3f9defc5e868a\` FOREIGN KEY (\`eventId\`) REFERENCES \`events\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`event_proximity_features\` ADD CONSTRAINT \`FK_7728fb969df687ed5447391949c\` FOREIGN KEY (\`list_id\`) REFERENCES \`list\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`event_proximity_features\` ADD CONSTRAINT \`FK_aab17170af27c0d9d236f263aeb\` FOREIGN KEY (\`address_id\`) REFERENCES \`addresses\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`event_dedup_candidates\` ADD CONSTRAINT \`FK_5afc26ab2c80d0c97fd0c4386eb\` FOREIGN KEY (\`canonicalEventId\`) REFERENCES \`events\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`event_dedup_candidates\` ADD CONSTRAINT \`FK_013d6f814e9971ea57a8429ebe4\` FOREIGN KEY (\`duplicateEventId\`) REFERENCES \`events\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`communication_events\` ADD CONSTRAINT \`FK_b7c80f5204029037f1bff141896\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ask_urban_messages\` ADD CONSTRAINT \`FK_c092a70dfc82d31a8089003daf5\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`analise_endereco_evento\` ADD CONSTRAINT \`FK_fa0bdd6f64a30fff722816aec85\` FOREIGN KEY (\`evento_id\`) REFERENCES \`events\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`analise_endereco_evento\` ADD CONSTRAINT \`FK_b23c341d8169359cffa4a12cf1e\` FOREIGN KEY (\`endereco_id\`) REFERENCES \`addresses\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`analise_endereco_evento\` ADD CONSTRAINT \`FK_55e001f245eefed8c406e4760cc\` FOREIGN KEY (\`usuario_proprietario_id\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`airbnb_pricing_attempt_logs\` ADD CONSTRAINT \`FK_a0e906a318d154c9ce60fe82319\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`airbnb_pricing_attempt_logs\` ADD CONSTRAINT \`FK_b80d3d1e8f3acad5605d4648f76\` FOREIGN KEY (\`list_id\`) REFERENCES \`list\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`airbnb_pricing_attempt_logs\` ADD CONSTRAINT \`FK_883535bd8bc877c20ff183695e7\` FOREIGN KEY (\`address_id\`) REFERENCES \`addresses\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`email_confirmations\` ADD CONSTRAINT \`FK_930e1d7c0171d23e5535b1e3873\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
        // Reverte só se as tabelas core foram criadas por esta migration.
        // Drop em ordem reversa de dependência (FKs caem junto no MySQL com SET FOREIGN_KEY_CHECKS).
        await queryRunner.query('SET FOREIGN_KEY_CHECKS=0');
        await queryRunner.query('DROP TABLE IF EXISTS `user`');
        await queryRunner.query('DROP TABLE IF EXISTS `addresses`');
        await queryRunner.query('DROP TABLE IF EXISTS `list`');
        await queryRunner.query('DROP TABLE IF EXISTS `events`');
        await queryRunner.query('DROP TABLE IF EXISTS `plans`');
        await queryRunner.query('DROP TABLE IF EXISTS `payment`');
        await queryRunner.query('DROP TABLE IF EXISTS `process_status`');
        await queryRunner.query('DROP TABLE IF EXISTS `analise_preco`');
        await queryRunner.query('DROP TABLE IF EXISTS `analise_endereco_evento`');
        await queryRunner.query('DROP TABLE IF EXISTS `email_confirmations`');
        await queryRunner.query('DROP TABLE IF EXISTS `notifications`');
        await queryRunner.query('SET FOREIGN_KEY_CHECKS=1');
  }
}
