import { Injectable, Logger } from '@nestjs/common';
import { Cron, CronExpression } from '@nestjs/schedule';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Event } from '../entities/events.entity';
import { MapsService } from '../maps/maps.service';
import { CoverageService } from './coverage.service';
import { isGoogleMapsConfigurationError } from '../maps/google-maps-error';

export interface GeocoderRunSummary {
  attempted: number;
  succeeded: number;
  failed: number;
  failures: Array<{ id: string; reason: string }>;
}

export interface GeocoderLastRun extends GeocoderRunSummary {
  startedAt: string;
  finishedAt: string;
  durationMs: number;
  status: 'success' | 'partial_failure' | 'failed' | 'error';
  errorMessage?: string;
}

/**
 * EventsGeocoderService - F6.2 Plus.
 *
 * Resolves the pending geocoding queue generated by collectors that ingest
 * events without lat/lng (`pendingGeocode=true`, `ativo=false`).
 */
@Injectable()
export class EventsGeocoderService {
  private readonly logger = new Logger(EventsGeocoderService.name);
  private running = false;
  private lastRun: GeocoderLastRun | null = null;

  constructor(
    @InjectRepository(Event) private readonly eventRepo: Repository<Event>,
    private readonly mapsService: MapsService,
    private readonly coverage: CoverageService,
  ) {}

  @Cron(CronExpression.EVERY_30_MINUTES)
  async cronTick() {
    if (this.running) {
      this.logger.warn('Geocoder run ja em andamento - skipando este tick');
      return;
    }
    this.running = true;
    try {
      await this.runOnce(30);
    } finally {
      this.running = false;
    }
  }

  async runOnce(limit = 30): Promise<GeocoderRunSummary> {
    const startedAt = new Date();

    try {
      const pending = await this.eventRepo.find({
        where: { pendingGeocode: true },
        order: { createdAt: 'ASC' },
        take: Math.max(1, Math.min(100, limit)),
      });

      if (pending.length === 0) {
        return this.rememberRun(startedAt, {
          attempted: 0,
          succeeded: 0,
          failed: 0,
          failures: [],
        });
      }

      let succeeded = 0;
      let attempted = 0;
      const failures: Array<{ id: string; reason: string }> = [];

      for (const ev of pending) {
        try {
          attempted++;
          const result = await this.mapsService.updateLatLngByEventId(ev.id);
          if (result?.ok && Number.isFinite(result.lat) && Number.isFinite(result.lng)) {
            const inCoverage = await this.coverage.isWithinCoverage(
              Number(result.lat),
              Number(result.lng),
            );
            await this.eventRepo.update(
              { id: ev.id },
              {
                pendingGeocode: false,
                outOfScope: !inCoverage,
                ativo: inCoverage,
              },
            );
            succeeded++;
          } else {
            const reason = result?.message ?? 'unknown';
            failures.push({ id: ev.id, reason });
            if (isGoogleMapsConfigurationError(reason)) {
              this.logger.warn(
                `Geocoder interrompido apos falha de configuracao Google Maps: ${reason}`,
              );
              break;
            }
          }
        } catch (err: any) {
          const reason = err?.message ?? 'exception';
          failures.push({ id: ev.id, reason });
          if (isGoogleMapsConfigurationError(err) || isGoogleMapsConfigurationError(reason)) {
            this.logger.warn(
              `Geocoder interrompido apos excecao de configuracao Google Maps: ${reason}`,
            );
            break;
          }
        }
      }

      this.logger.log(
        `Geocoder run: attempted=${attempted}, succeeded=${succeeded}, failed=${failures.length}`,
      );

      return this.rememberRun(startedAt, {
        attempted,
        succeeded,
        failed: failures.length,
        failures,
      });
    } catch (err: any) {
      this.lastRun = this.buildLastRun(
        startedAt,
        { attempted: 0, succeeded: 0, failed: 0, failures: [] },
        'error',
        err?.message ?? 'exception',
      );
      throw err;
    }
  }

  async pendingCount(): Promise<number> {
    return this.eventRepo.count({ where: { pendingGeocode: true } });
  }

  async status() {
    return {
      pendingGeocode: await this.pendingCount(),
      readiness: this.mapsService.getGeocodingReadiness(),
      running: this.running,
      lastRun: this.lastRun,
    };
  }

  private rememberRun(startedAt: Date, summary: GeocoderRunSummary): GeocoderRunSummary {
    let status: GeocoderLastRun['status'] = 'success';
    if (summary.failed > 0 && summary.succeeded > 0) status = 'partial_failure';
    if (summary.failed > 0 && summary.succeeded === 0) status = 'failed';
    this.lastRun = this.buildLastRun(startedAt, summary, status);
    return summary;
  }

  private buildLastRun(
    startedAt: Date,
    summary: GeocoderRunSummary,
    status: GeocoderLastRun['status'],
    errorMessage?: string,
  ): GeocoderLastRun {
    const finishedAt = new Date();
    return {
      ...summary,
      startedAt: startedAt.toISOString(),
      finishedAt: finishedAt.toISOString(),
      durationMs: finishedAt.getTime() - startedAt.getTime(),
      status,
      ...(errorMessage ? { errorMessage } : {}),
    };
  }
}
