import {
  Body,
  Controller,
  Get,
  HttpCode,
  Post,
  Query,
  Req,
  UploadedFile,
  UseGuards,
  UseInterceptors,
} from '@nestjs/common';
import { FileInterceptor } from '@nestjs/platform-express';
import { ApiBearerAuth, ApiBody, ApiConsumes, ApiHeader, ApiOperation, ApiTags } from '@nestjs/swagger';
import { Throttle } from '@nestjs/throttler';
import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import { RolesGuard } from '../auth/roles.guard';
import { Roles } from '../auth/roles.decorator';
import { AdminAuditService } from '../admin-audit/admin-audit.service';
import {
  EventsIngestService,
  IngestBatchResponse,
} from './events-ingest.service';
import { EventsGeocoderService } from './events-geocoder.service';
import { EventsCsvImportService } from './events-csv-import.service';
import { EventsCollectorRequestContext, EventsIngestApiKeyGuard } from './events-ingest-api-key.guard';
import { ImportEventsCsvDto, IngestEventsBatchDto } from './events-ingest.dto';

/**
 * Endpoint universal de ingestão de eventos (F6.2 Plus).
 *
 * Camadas que batem aqui:
 *  - Camada 1: clientes Python das APIs oficiais (api-football, Sympla, etc.)
 *  - Camada 2: pipeline Firecrawl
 *  - Camada 3: form admin de curadoria + import CSV
 *
 * Acesso restrito a role `admin` — coletores autenticam com um usuário
 * técnico admin (criado manualmente no DB) cujo JWT é setado em env var
 * dos serviços coletores.
 *
 * Throttle relaxado (60/min) porque batches diários costumam ser 1
 * request com 100-500 eventos.
 */
@ApiTags('events-ingest')
@ApiBearerAuth()
@Controller('events')
export class EventsIngestController {
  constructor(
    private readonly ingest: EventsIngestService,
    private readonly geocoder: EventsGeocoderService,
    private readonly csvImport: EventsCsvImportService,
    private readonly audit: AdminAuditService,
  ) {}

  @Throttle({ default: { ttl: 60_000, limit: 60 } })
  @UseGuards(EventsIngestApiKeyGuard)
  @ApiHeader({
    name: 'x-urban-events-ingest-key',
    required: true,
    description: 'Service-account key scoped to events ingestion. Configure EVENTS_INGEST_API_KEY.',
  })
  @ApiHeader({
    name: 'x-urban-collector',
    required: false,
    description: 'Stable collector name for audit metadata.',
  })
  @ApiHeader({
    name: 'x-urban-collector-version',
    required: false,
    description: 'Collector version or build SHA for audit metadata.',
  })
  @ApiHeader({
    name: 'x-urban-ingest-run-id',
    required: false,
    description: 'Run id generated by the collector/orchestrator.',
  })
  @ApiOperation({
    summary:
      'Ingere um lote de eventos via service account. Idempotente por dedupHash; UPSERT conservador.',
  })
  @Post('ingest')
  @HttpCode(200)
  async ingest_(
    @Body() body: IngestEventsBatchDto,
    @Req() req: { collector?: EventsCollectorRequestContext },
  ): Promise<IngestBatchResponse> {
    const events = body?.events ?? [];
    const result = await this.ingest.ingestBatch(events);
    const collector = req.collector ?? {
      actor: 'events-collector',
      collectorVersion: null,
      ingestRunId: null,
    };
    await this.audit.record({
      actorUserId: collector.actor,
      action: 'events.ingest.batch',
      entityType: 'events',
      entityId: collector.ingestRunId,
      after: {
        total: result.total,
        created: result.created,
        updated: result.updated,
        skipped: result.skipped,
      },
      metadata: {
        collector: collector.actor,
        collectorVersion: collector.collectorVersion,
        ingestRunId: collector.ingestRunId,
        bySource: result.bySource,
      },
    });
    return result;
  }

  @ApiOperation({
    summary: 'Status da fila de geocoding pendente (eventos sem lat/lng)',
  })
  @Get('geocoder/status')
  @UseGuards(JwtAuthGuard, RolesGuard)
  @Roles('admin')
  async geocoderStatus() {
    return this.geocoder.status();
  }

  @Throttle({ default: { ttl: 60_000, limit: 5 } })
  @ApiOperation({
    summary:
      'Dispara o geocoder agora (em vez de esperar o cron 30 min). Limit default 30.',
  })
  @Post('geocoder/run')
  @HttpCode(200)
  @UseGuards(JwtAuthGuard, RolesGuard)
  @Roles('admin')
  async geocoderRun(@Query('limit') limit: string = '30') {
    return this.geocoder.runOnce(parseInt(limit, 10));
  }

  @Throttle({ default: { ttl: 60_000, limit: 10 } })
  @ApiOperation({
    summary:
      'Importa eventos via upload de arquivo CSV (Camada 3 — curadoria humana). Max 1000 linhas, 5MB.',
  })
  @ApiConsumes('multipart/form-data')
  @ApiBody({
    schema: {
      type: 'object',
      properties: {
        file: { type: 'string', format: 'binary' },
        sourceLabel: { type: 'string', example: 'admin-csv-import' },
      },
    },
  })
  @Post('import-csv')
  @HttpCode(200)
  @UseGuards(JwtAuthGuard, RolesGuard)
  @Roles('admin')
  @UseInterceptors(
    FileInterceptor('file', {
      limits: { fileSize: 5 * 1024 * 1024 }, // 5MB
    }),
  )
  async importCsv(
    @UploadedFile() file: { buffer: Buffer; originalname?: string; size: number },
    @Body() body: ImportEventsCsvDto,
  ) {
    if (!file) {
      throw new Error('arquivo CSV obrigatório (campo "file" no multipart)');
    }
    return this.csvImport.importFromBuffer(file.buffer, body.sourceLabel);
  }
}
