include:
  - project: 'infra/templates'
    file: 'deploy-master.yml'

variables:
  APP_DOMAIN: ""
  PORT: "6800"
  USE_GPU: "false"
  USE_HTTPS: "false"
  K8S_ENV_INJECT: "ASSUME_ROLE_ARN ASSUME_ROLE_EXTERNAL_ID AWS_ACCESS_KEY_ID AWS_REGION AWS_SECRET_ACCESS_KEY DB_HOST DB_NAME DB_PASSWORD DB_PORT DB_USER TICKETMASTER_API_KEY"
