export enum ErrorCode {
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    CUSTOMER_CREATION_FAILED = 'CUSTOMER_CREATION_FAILED',
    AUTH_REGISTRATION_FAILED = 'AUTH_REGISTRATION_FAILED',
    UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  }